<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.grocery</groupId>
    <artifactId>smart-grocery-store-management-system</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>smart-grocery-store-management-system</name>

    <modules>
        <module>infrastructure/discovery-server</module>
        <module>infrastructure/config-server</module>
        <module>infrastructure/api-gateway</module>
        <module>services/auth-service</module>
        <module>services/catalog-service</module>
        <module>services/inventory-service</module>
        <module>services/notification-service</module>
        <module>services/order-service</module>
        <module>services/promotion-service</module>
        <module>services/chat-service</module>
    </modules>
</project>
