spring.application.name=notification-service
server.port=${SERVER_PORT:8084}

spring.datasource.url=${NOTIFICATION_DB_URL:jdbc:mysql://localhost:3306/grocery_notification_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${NOTIFICATION_DB_USERNAME:root}
spring.datasource.password=${NOTIFICATION_DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

app.messaging.order.exchange=order.events
app.messaging.order.created.queue=notification.order-created.queue
app.messaging.order.created.dlq=notification.order-created.dlq
app.messaging.order.created.routing-key=order.created

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
