version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: grocery_db
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "grocery_db"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - grocery_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: grocery_backend
    ports:
      - "8080:8080" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/grocery_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend/product-images:/app/product-images
      - ./backend/user-photos:/app/user-photos
    depends_on:
      db:
        condition: service_healthy
    networks:
      - grocery_network

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
    container_name: grocery_frontend
    ports:
      - "80:80" 
    depends_on:
      - backend
    networks:
      - grocery_network

networks:
  grocery_network:
    driver: bridge

volumes:
  db_data:
